### ISSUE TITLE
BUG: Terrain shader has inverted/wrong shadows/shading

### ISSUE THREAD

**Issue by oyvind-stromsvik** [briochie/wow.unity#6]
Here's a screenshot where I've replaced all the tiles around this tile with actual Unity terrain, which has correct shading, and you can see from the tree in the lower right corner where the directional light is coming from:
![Screenshot 2023-06-06 135540](https://github.com/briochie/wow.unity/assets/2248910/86212024-f612-4449-8be5-32b3be9859bc)

I actually didn't notice this before I replaced my tiles with Unity terrain, and thought it was the terrain that was wrong, but it seems like the shader in this package is putting the side facing the directional light in shadow or something?

**Comment by briochie** [comment]
Weird. The shading uses the out-of-the-box lighting for URP. Unless something extra strange is going on with the coordinate system changes, I don't see why that would be the case.

If I were to guess, the terrain is using a more custom lighting implementation than the standard URP lighting. Going to close this issue, since this will be something that comes up with the terrain changes regardless.

**Comment by briochie** [comment]
Fixing the close type
